
const DOCUMENTS = require('../util/constants.json').documents.type;

module.exports ={"id" : 1,
    "type" : DOCUMENTS.sectors,
    "data" : [
      {"id" : 1, "id" : 1, "name" : "Accounting", "desc" : ""},
      {"id" : 2, "name" : "Advertising", "desc" : ""},
      {"id" : 3, "name" : "Aerospace", "desc" : ""},
      {"id" : 4, "name" : "Agriculture & Agribusiness", "desc" : ""},
      {"id" : 5, "name" : "Air Transportation", "desc" : "" },
      {"id" : 6, "name" : "Apparel & Accessories"},
      {"id" : 7, "name" : "Auto", "desc" : ""},
    	{"id" : 8, "name" : "Banking", "desc" : ""},
    	{"id" : 9, "name":"Beauty & Cosmetics", "desc" : ""},
    	{"id" : 10, "name" : "Biotechnology", "desc" : ""},
    	{"id" : 11, "name" : "Chemical", "desc" : ""},
    	{"id" : 12, "name" : "Communications", "desc" : ""},
    	{"id" : 13, "name" : "Computer", "desc" : ""},
    	{"id" : 14, "name" : "Construction", "desc" : ""},
    	{"id" : 15, "name" : "Consulting" , "desc" : ""},
    	{"id" : 16, "name" : "Consumer Products", "desc" : ""},
    	{"id" : 17, "name" : "Education", "desc" : ""},
    	{"id" : 18, "name" : "Electronics", "desc" : ""},
    	{"id" : 19, "name" : "Employment", "desc" : ""},
    	{"id" : 20, "name" : "Energy" , "desc" : ""},
    	{"id" : 21, "name" : "Entertainment & Recreation", "desc" : ""},
    	{"id" : 22, "name" : "Fashion", "desc" : ""},
    	{"id" : 23, "name" : "Financial Services", "desc" : ""},
    	{"id" : 24, "name": "Fine Arts", "desc" : ""},
    	{"id" : 25, "name": "Food & Beverage", "desc" : ""},
    	{"id" : 26, "name": "Green Technology", "desc" : ""},
    	{"id" : 27, "name": "Health", "desc" : ""},
    	{"id" : 28, "name": "	Information", "desc" : ""},
    	{"id" : 29, "name": "Information Technology", "desc" : ""},
    	{"id" : 30, "name": "Insurance", "desc" : ""},
    	{"id" : 31, "name": "Journalism & News", "desc" : ""},
    	{"id" : 32, "name": "Legal Services", "desc" : ""},
    	{"id" : 33, "name": "Manufacturing", "desc" : ""},
    	{"id" : 34, "name": "Media & Broadcasting", "desc" : ""},
    	{"id" : 35, "name": "Medical Devices & Supplies", "desc" : ""},
    	{"id" : 36, "name": "Motion Pictures & Video", "desc" : ""},
    	{"id" : 37, "name": "Music", "desc" : ""},
    	{"id" : 38, "name": "Pharmaceutical", "desc" : ""},
    	{"id" : 39, "name": "Public Relations", "desc" : ""},
    	{"id" : 40, "name": "Publishing", "desc" : ""},
    	{"id" : 41, "name": "Real Estate", "desc" : ""},
    	{"id" : 42, "name": "Retail", "desc" : ""},
    	{"id" : 43, "name": "Service", "desc" : ""},
    	{"id" : 44, "name": "Sports", "desc" : ""},
    	{"id" : 45, "name": "Technology", "desc" : ""},
    	{"id" : 46, "name": "Telecommunications", "desc" : ""},
    	{"id" : 47, "name": "Tourism", "desc" : ""},
    	{"id" : 48, "name": "Transportation", "desc" : ""},
    	{"id" : 49, "name": "Travel", "desc" : ""},
    	{"id" : 50, "name": "Utilities", "desc" : ""},
    	{"id" : 51, "name": "Video Game ", "desc" : ""},
    	{"id" : 52, "name": "Web Services", "desc" : ""}
  ]
};

console.log(module.exports);
